name: Deploy to Dreamhost
run-name: ${{ github.actor }} is pushing to Dreamhost!
on: [push]
jobs:
  Push-To-Dreamhost:
    runs-on: push
    steps:
      # - run: echo " Job was triggered by a ${{ github.event_name }} event."
      # - name: Install SSH Key
      #   uses: shimtaro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.DREAMHOST_SECRET }}
      #     known_hosts: 'derp'
      # - name: Adding Known Hosts
      #   run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Build project
        run: npm run build
      
      # - name: Deploy into Dreamhost
      #   run: rsync -avz ./dist/ ${{ secrets.SSH_USER
