name: Deploy to Dreamhost
run-name: ${{ github.actor }} is pushing to Dreamhost!
on: [push]
jobs:
  Push-To-Dreamhost:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DREAMHOST_SECRET }}
          known_hosts: 'derp'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: See known hosts
        run: cat ~/.ssh/known_hosts
      - name: Deploy into Dreamhost  
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avz
          path: /out/
          remote_path: /home/dh_uxcu3k/samira.villamor.io
          remote_host: tigard.dreamhost.com
          remote_user: dh_uxcu3k
          remote_password: ${{secrets.DREAMHOST_PASSWORD}}
          remote_key: ${{secrets.SSH_HOST}}
